// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqUFVMt3-mmschKVQKhc2j9cGNIbksxuE',
    appId: '1:1001950507072:web:0303f4537c42eaa1c5efa5',
    messagingSenderId: '1001950507072',
    projectId: 'password-manager-4197c',
    authDomain: 'password-manager-4197c.firebaseapp.com',
    storageBucket: 'password-manager-4197c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmKoc243ADGBXQjaELzpYcwak9SZee1Hw',
    appId: '1:1001950507072:android:f88278458b433ad1c5efa5',
    messagingSenderId: '1001950507072',
    projectId: 'password-manager-4197c',
    storageBucket: 'password-manager-4197c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASjEn7Z_WXUmpNOrjrA6Sjezcp071RZAQ',
    appId: '1:1001950507072:ios:da6a9b7d635bdc79c5efa5',
    messagingSenderId: '1001950507072',
    projectId: 'password-manager-4197c',
    storageBucket: 'password-manager-4197c.firebasestorage.app',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASjEn7Z_WXUmpNOrjrA6Sjezcp071RZAQ',
    appId: '1:1001950507072:ios:da6a9b7d635bdc79c5efa5',
    messagingSenderId: '1001950507072',
    projectId: 'password-manager-4197c',
    storageBucket: 'password-manager-4197c.firebasestorage.app',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqUFVMt3-mmschKVQKhc2j9cGNIbksxuE',
    appId: '1:1001950507072:web:1e3d0b3319e0a888c5efa5',
    messagingSenderId: '1001950507072',
    projectId: 'password-manager-4197c',
    authDomain: 'password-manager-4197c.firebaseapp.com',
    storageBucket: 'password-manager-4197c.firebasestorage.app',
  );
}
